App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -180
          max: 180
          groups: ['create', 'edit']

App\Entity\Measurement:
  properties:
    celsius:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -80
          max: 60
          groups: ['create', 'edit']